http_addr: ":8080"

jwt:
  issuer: "neoneuro"
  audience: "neoneuro-client"
  alg: "HS256"
  secret: ""  # 留空；请通过环境变量 JWT_SECRET 提供

log:
  level: "info"           # debug/info/warn/error
  file: "log/app.log"     # 相对 backend 工作目录
  max_size: 100           # MB
  max_backups: 7
  max_age: 14             # days
  compress: true
